// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvc9d5n8XcnEdyYNmzX_DniMp-VBOU7K8',
    appId: '1:676003706096:web:14a03c8c1788c02d1cbe35',
    messagingSenderId: '676003706096',
    projectId: 'mobileapp-hw6-2c905',
    authDomain: 'mobileapp-hw6-2c905.firebaseapp.com',
    storageBucket: 'mobileapp-hw6-2c905.appspot.com',
    measurementId: 'G-E6PDNKP2GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3yTFv97PE3-3junRZFx5PCF0kMrwmb8',
    appId: '1:676003706096:android:dc721f90b27d7df21cbe35',
    messagingSenderId: '676003706096',
    projectId: 'mobileapp-hw6-2c905',
    storageBucket: 'mobileapp-hw6-2c905.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLbYxwicrc6kNXf4Qzn1I4-uNEDLUEHIQ',
    appId: '1:676003706096:ios:554c31549c58c0211cbe35',
    messagingSenderId: '676003706096',
    projectId: 'mobileapp-hw6-2c905',
    storageBucket: 'mobileapp-hw6-2c905.appspot.com',
    iosBundleId: 'com.dattran.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLbYxwicrc6kNXf4Qzn1I4-uNEDLUEHIQ',
    appId: '1:676003706096:ios:d17718d3e7b565631cbe35',
    messagingSenderId: '676003706096',
    projectId: 'mobileapp-hw6-2c905',
    storageBucket: 'mobileapp-hw6-2c905.appspot.com',
    iosBundleId: 'com.dattran.hw4.RunnerTests',
  );
}
